trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  loop: for i in {1..10}; do echo "doing stuff..."; sleep .5; done;

jobs:
  - job: Build
    displayName: Build and test app
    steps:
      # - task: NodeTool@0
      #   displayName: Install Node 14.15.4
      #   inputs:
      #     versionSource: 'spec'
      #     versionSpec: '14.15.4'

      - bash: |
          echo 'npm ci'
          for i in {1..10}; do echo "doing stuff..."; sleep .5; done;
        displayName: Install frontend dependencies

      - bash: |
          echo 'npm run test'
          ${{ variables.loop }}
        displayName: Run frontend tests

      # - bash: |
      #     echo 'npm run build'
      #     source spinner.sh
      #   displayName: Build frontend

      # #   - task: S3Upload@1
      # #     displayName: Deploy frontend
      # #     inputs:
      # #       awsCredentials: 'fake-credentials'
      # #       regionName: 'us-east-1'
      # #       bucketName: 'fake-bucket'
      # #       globExpressions: '**'
      # #       targetFolder: 'fake-folder'
      # #       sourceFolder: 'path/to/frontend/build'

      # - bash: |
      #     echo 'dotnet restore'
      #     source spinner.sh
      #   displayName: Restore backend

      # - bash: |
      #     echo 'dotnet test'
      #     source spinner.sh
      #   displayName: Run backend tests

      # - bash: |
      #     echo 'dotnet publish'
      #     source spinner.sh
      #   displayName: Publish backend

      #   - task: BeanstalkDeployApplication@1
      #     displayName: Deploy to Elastic Beanstalk
      #     inputs:
      #         awsCredentials: 'fake-credentials'
      #         regionName: 'us-east-1'
      #         applicationName: 'fake-app'
      #         environmentName: 'fake-environment'
      #         applicationType: 'aspnet'
      #         webDeploymentArchive: 'path/to/release-bundle.zip'
