trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: text
    type: string
    default: doing stuff...
    values:
      - doing stuff...
      - loading...
      - waiting...

variables:
  loop: for i in {1..10}; do echo ${{ parameters.text }}; sleep .5; done;

jobs:
  - job: Build
    displayName: Build and test app
    steps:

      - bash: |
          echo 'npm ci'
          ${{ variables.loop }}
        displayName: Install frontend dependencies

      - bash: |
          echo 'npm run test'
          ${{ variables.loop }}
        displayName: Run frontend tests

      - bash: |
          echo 'npm run build'
          ${{ variables.loop }}
        displayName: Build frontend

      - bash: |
          echo 'dotnet restore'
          ${{ variables.loop }}
        displayName: Restore backend

      - bash: |
          echo 'dotnet test'
          ${{ variables.loop }}
        displayName: Run backend tests

      - bash: |
          echo 'dotnet publish'
          ${{ variables.loop }}
        displayName: Publish backend

      - script: echo '##vso[build.addbuildtag]Success
        displayName: add environment tag
