trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: environment
    type: string
    default: working
    values:
      - working
      - staging
      - production

variables:
  ${{ if eq( parameters.environment, 'working' ) }}:
    isWorking: true

  ${{ if eq( parameters.environment, 'staging' ) }}:
    isStaging: true

  ${{ if eq( parameters.environment, 'production' ) }}:
    isProduction: true

jobs:
  - ${{ if eq( variables.isWorking, true )}}:
      - template: templates/working.yml

  - ${{ if eq( variables.isStaging, true )}}:
      - template: templates/staging.yml

  - ${{ if eq( variables.isProduction, true )}}:
      - template: templates/production.yml
