jobs:
  - job: Build
    displayName: Build app
    steps:
      - template: steps.yml
        parameters:
          tag: staging
          loop: for i in {1..10}; do echo "waiting..."; sleep .5; done;
