jobs:
  - job: Build
    displayName: Build app
    variables:
      loop: for i in {1..10}; do echo "doing stuff..."; sleep .5; done;
    steps:
      - template: steps.yml
        parameters:
          tag: working
